### ISSUE TITLE
Japan JPY / BTC Market Maker Bounty

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#138]
To claim this bounty the contributor must make a market in Bisq JPY/BTC for 1 month.

This will involve:

1. Keeping at least **2 BUY** and **2 SELL** offers live during 1 month.

2. Attracting other traders to the market through marketing, communication.

3. Completing at least 5 trades.

4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

5. Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

### Bounty: 1000 $BSQ

**Comment by torachan3** [comment]
I started working on this in hopes of getting this bounty.

I put up 2 BUY and 2 SELL orders a couple of days ago. They are small to get things started.

I also posted on reddit at [/r/japanlife](https://www.reddit.com/r/japanlife/comments/c5reqm/bisq_a_decentralized_p2p_bitcoin_exchange_jpybtc/) to hopefully attract some new traders and get the market moving.

**Comment by jmaurice** [comment]
I claim this bounty.

> Keeping at least 2 BUY and 2 SELL offers live during 1 month.

I've had up to 9 JPY offers up at once, for F2F trades in 2 different cities in Japan. The number of offers varies as offers get accepted, but I have setup a new dedicated desktop PC at home to maintain at least 2 buy and 2 sell offers at all times. I will maintain this and continue to provide liquidity indefinitely, much longer than 1 month, as it's a nice source of income and good for the community :)

> Attracting other traders to the market through marketing, communication.

1) I did a 20 minute presentation about Bisq, including a live demo trade, at the June 19 meetup of Tokyo Bitcoin Hackers to about 30 ~ 40 people. As localbitcoins recently removed cash trades, the audience was extremely interested, and I even noticed some members of major centralized Bitcoin exchanges in Tokyo came to see the presentation and learn about Bisq.

2) I did an hour long seminar about Bisq, including several live demo trades, at the July 3 meetup of Kanazawa Bitcoin Hackers, to 3 people (countryside community is smaller than Tokyo). The audience are mostly newcomers to Bitcoin, but they instantly loved it and I think P2P community in Kanazawa will actually start faster than Tokyo because of the smaller community size, but will continue to hype it up in Tokyo as well. I think the biggest missing piece was a lack of any standing offers on the order book, but I am providing that now.

3) I discussed Bisq on Twitter(@wiz) in several different threads during the past month or so, including the BSQ token, the trade experience, etc. and will continue to do so as I'm now using Bisq actively.

> Completing at least 5 trades.

I was either a maker or taker to the last 10 JPY trades, including the following recent ones:
```
UVGGNZA-f2d2846b-4a85-45bf-b004-5d4a129dff07-112
646434-8b746385-0c84-463b-b2d5-1cf495423993-112
AMYPZ-61fd4139-2f79-4ca5-a52a-f5d093a718a7-112
446510-2566f702-17cb-4f52-92a4-a121139323b4-112
QBWZBPUW-d04cc692-4a7c-4639-9c5e-a56a0f7136d3-112
```

> Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

1) All trades so far were done using F2F cash exchange, but domestic bank transfer is also quite interesting to us, and I think we want to try that next now that large banks in Japan support 24/7/365 instant transfers. Of course, privacy being the primary goal of Bisq, together with the recent localbitcoins removing cash trades, I would predict F2F cash will be 90% of the trade volume. 

2) Of course the most obvious problem was that newbies need Bitcoin in their Bisq wallet (for security deposit) to buy Bitcoin, which they don't yet have. Additional problems encountered and suggestions for improvement are more detailed in my Bisq Network Proposal 98: Adjust parameters for JPY order book to reduce friction for new users https://github.com/bisq-network/proposals/issues/98 

3) As I do not yet possess any BSQ tokens, I paid all fees in Bitcoin. So far the trade amounts have been the minimum amount, as we are just starting out and teaching people how to use Bisq, so the percentage of trade/mining fees was quite high. I understand this gets much more reasonable with larger trade amounts, but of course if you can waive trading fees temporarily to help the JPY market develop that would be greatly appreciated - I also mentioned this in the above proposal. 

> Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

I attended at least 1 live Bisq Growth call in June and would be happy to attend another one in July to give additional feedback. Let me know when is convenient time :)

Thank you.

**Comment by torachan3** [comment]
I bow out. :) @jmaurice 100% deserves this bounty. I only learned about Bisq through his demo on June 19 meetup of Tokyo Bitcoin Hackers. I had know idea how much he had invested in this. I only was going to attempt because I stumbled across the bounty and saw there there were no open orders at the time. Maybe I will take on one of his orders just to try the process out!

**Comment by jmaurice** [comment]
Hey @torachan3, I don't recognize your pseudonymous identity, but thanks for supporting Bisq in Japan and coming to the Tokyo Bitcoin Hackers meetup. Yesterday when I saw your post, I assumed you had given up on this since your post got deleted from reddit and I didn't see your offers online, but now I see you put them back. Thanks for providing liquidity, but I think your 30% premium is quite steep, maybe consider lowering it to 10% for now? :)

I actually suggested to @flix1 back in June that this bounty should be distributed amongst several people, but unfortunately it seems nobody else has answered the call to provide liquidity (except you), so yesterday I setup a dedicated PC for this and loaded the wallet and created some standing offers.

If you're going to be providing liquidity over the next month then of course you should get some of the bounty as well. Recently I've been more aggressively pushing Bisq and I have another friend who's also going to create some offers, so hopefully we can get some nice market going more than just demo trades. If @flix1 is okay with awarding the bounty to me, I will distribute the tokens to @torachan3 and other JPY traders over the next month. If you have Keybase, DM me (wiz) or join the Tokyo Bitcoin Hackers chat group.

**Comment by flix1** [comment]
Very nice to see that JPY/BTC has taken off!

![image](https://user-images.githubusercontent.com/4233784/60709240-3e98b880-9f10-11e9-92df-b70099fd80f4.png)

![image](https://user-images.githubusercontent.com/4233784/60709302-62f49500-9f10-11e9-9949-d76b18e1916e.png)

Congratulations @jmaurice on claiming the bounty!
