### ISSUE TITLE
Japan: Complete the 1st F2F trade in JPY/BTC

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#139]
Complete the first face-to-face trade in Japanese Yen (JPY/BTC) on Bisq.

Report back here with 3 lines of feedback on the details of the trade (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

### Bounty: 50 $BSQ

**Comment by tdhr0917** [comment]
1) Payment method used was F2F cash in Kanazawa, Japan
2) Problems encountered were having to deposit Bitcoin for security deposit
3) Suggestion for improvement: make security deposit optional
4) Fees paid are in attached screenshot
5) Time it took was instant, since F2F in-person trade
I did the first JPY trade with @jmaurice on June 12
![スクリーンショット 2019-07-05 4 21 04](https://user-images.githubusercontent.com/52544335/60685136-69691980-9edc-11e9-870d-72533a51e39d.png)

**Comment by flix1** [comment]
Congratulations @tdhr0917 on claiming the bounty!

**Comment by jmaurice** [comment]
Can confirm, first trade was with @tdhr0917 👍
