### ISSUE TITLE
Japan: JPY Liquidity Party  [June 19 2019]

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#140]
### What
On 19 June 2019 we will try to kick-start the JPY/BTC market

### Objective
Reach 10+ live offers in JPY/BTC market.

### Bounty
Participants in the experiment (creating at least 1 offer on this day) will be rewarded with **20 $BSQ** after posting feedback here.

Additionally there will be **BTC bounties** offered by collaborators to be announced during the event.

Please add a 👍 below if you will participate!

**Comment by flix1** [comment]
In collaboration with Tokyo Bitcoin Meetup

Wednesday, 19 June 2019
https://www.meetup.com/en-AU/Tokyo-Bitcoin-Hackers/events/262055716/

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/59906548-46813480-9409-11e9-9583-8fcaa60e53bf.png)

This was moderately successfull. The maximum number of live offers reached was 6.

**Comment by jmaurice** [comment]
Unfortunately nobody participated in the Liquidity Party on that particular day. However @torachan3 did create offers as a direct result of the event, and a few other guys are going to soon. So I would request to change this bounty to anyone who creates offers within 30 days of the meetup presentation. Is that reasonable?

**Comment by flix1** [comment]
I think that nobody will object to @torachan3 claiming the bounty a bit late. 

We are always happy to encourage contributors to learn how to make their first compensation request to the DAO. This is as good an excuse as any.

@torachan3 go ahead and create your compensation request based on this bounty. I will definitely vote in favour in this voting cycle and I'm pretty sure so will everyone else.

**Comment by torachan3** [comment]
Okay, I will submit a compensation request :)

**Comment by torachan3** [comment]
I claim this bounty. Although I did not create an offer on the day of the Liquidity Party, I have begun using Bisq and creating orders as a result of learning about Bisq at this event. At first I had created 2 BUY and 2 SELL orders for about ~1000 yen each, but currently have 1 BUY and 1 SELL order up for about ~5000 yen each. I plan to keep these online to help with market liquidity.

Some feedback:
- First of all, I love the idea of a decentralized exchange like Bisq and look forward to its development and want it to succeed.
- I was a little surprised at how much of a "reserve" was required for some of the orders. Some of them were 5x the amount. I think this should be optional, instead of required. The person taking on an order should be able to see how much is in reserved (if anything.)
- At first I had created 2 BUY and 2 SELL orders for about ~1000 yen each. I chose this small amount because of the high "reserve" that was required, though with on-chain transaction fees that small of an amount becomes impractical.
- I would love to be able to run Bisq on a Raspberry Pi. I tried searching how to install it on a Pi and came across a couple threads, but it sounded like if you could even get it running it would be too slow to be usable.
- I'm having fun learning about Bisq and am having fun now learning how the DOA works as I begin to submit my compensation request!

![screen](https://user-images.githubusercontent.com/52248779/60769060-7406f700-a106-11e9-9735-fbebf5eb9532.png)
