### ISSUE TITLE
Language-specific communities & activities

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/growth#142]
There is a lot of activity among Spanish-speaking contributors as seen on Slack (meetups, liquidity weeks, interviews in Spanish, etc). Unfortunately, info on Slack tends to disappear after a while (because of our free subscription), so it would be great to pool all that info into one place, present it in a clear format and keep it updated. This format be used for other core Bisq languages as well (such as Portuguese, German, French, Russian, etc). I suggest the following format:

- Language
- Countries & ambassadors
- Activities
  - Translations
  - Liquidity weeks
  - Events (meetups & conferences)
  - Bounties
  - Interviews
  - Bitcoin/other cryptocurrency related news

Perhaps an ambassador for each language/country can be responsible for pooling, updating all the info and bringing new contributors onboard. We can set up bounties for doing that if needed, but I think there is already some interest among existing contributors, such as translators). 

We can have this info available either on [the Community page](https://bisq.network/community/) or on [the Forum](https://bisq.community/) and share that info on Bisq's Facebook page and other social media. Ideally, we should have this information available in English and the target language.

Here is an example for the Spanish-speaking page, based on the interest and activities on Slack (I apologize in advance for any mistakes in the names:)):

- Language: Spanish
- Countries & ambassadors
  -  Colombia: Ricardo  Saurio, Ricardo Martinez
  -  Mexico: Juan Sebastian Tellez
- Activities
  - Translations: Bisq website (WIP)
  - Liquidity weeks
  - Events (meetups in Mexico City, etc)
  - Interviews: with [@flix1](https://www.ivoox.com/l22-bisq-felix-moreno-parte-1-audios-mp3_rf_36772849_1.html)
  - Bitcoin-related news

I look forward to hearing your thoughts!!

**Comment by arunasurya** [comment]
I should probably mention that this task should be compensated, in case it wasn't clear. I am not sure if there should be a specific amount or the amount is determined by the work done/value produced.

**Comment by huey735** [comment]
I've been thinking about this. It'd be useful to provide those interested with information relevant to their markets. However, we need to be careful not try to do everything. I think we should look to focus only on information directly related to Bitcoin and Bisq.

**Comment by arunasurya** [comment]
Here are some ideas from the second translator call:
- The main goal for having language-specific information is to build communities in those languages.
- An ambassador can create a thread on Bisq forum, under "Protomotion", ideally in the target language (with a summary in English).
- An ambassador can create a Bisq account on Telegram in their target language since it may be a better place to answer questions for those who don't want to go to Bisq forum.
- Other platforms include Facebook and the Bitcon talk forum.
- It would be nice for an ambassador to be the owner of these specific tasks, and to be a go-to person if there is an interest from the outside world in that language.

**Comment by m52go** [comment]
This idea has been floated a couple times since it was proposed here but there hasn't been much activity on it. My guess is that localization is a significant task, and localized community-building is a massive task. I think it will need to be community-driven, and planning a top-down approach here won't be too effective.

We've already had some region-specific Twitter accounts pop up in the recent past, and have had meetup organizers in other countries reach out on their own.

I think those are the sorts of activities that will achieve the goal of this issue: organic interest driven by locals who know their people best.

Therefore I'll close this issue, but don't take that as a sign of disapproval. It's the opposite—this is a great idea! Anyone who's interested in building such a community should go about it in the typical way [outlined here](https://docs.bisq.network/contributor-checklist.html#do-valuable-work-and-get-compensated) for all Bisq contributions.
