### ISSUE TITLE
[Call] Q&A on Contributing: Bisq BRIEF for August 22

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#155]
## Call details

- **Date:** Thursday August 22 2019
 - **Time:** 11:15a–12:15p Pacific (PDT) / 8:15p–9:15p Central European (CEST)
 - **Place:** Zoom (details below)

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Also join the #growth channel on our Slack workspace for more discussion on Bisq growth initiatives.

## About

Topic for this event is **contributing to Bisq**.

The format for this call will be a free-form discussion/Q&A guided by the topics below. There will not be a lecture/presentation beforehand.

We will have a few contributors join to discuss various aspects:
* available work/priorities: for developers and non-developers
* how the Bisq DAO works for compensation
* Bisq "culture"
* first-hand accounts of why people contribute

And of course, we will weave in questions as they're suggested from attendees.

## Call details

Zoom link:
https://zoom.us/j/322825254

You can also join without Zoom software or registration:
https://zoom.us/wc/join/322825254?pwd=

**Comment by FKrauss** [comment]
Sending in some topics/questions as a first timer, non-dev and growth focused guy:

1. Looking at Bisq and other exchanges the landing pages seem to be great for an Open Source project, but not very welcoming for a new user specially a non technical one. Has anything been discussed in that front? maybe we create some specific landing pages for new users that are more focused on how to get started. We have a few things that can be leveraged here: no account needs to be created, it all runs in your computer

2. we briefly touched upon some geos and how to grow Bisq in a coordinated way. I saw that Bisq just started with the ARS/BTC pair. Can you elaborate on how that happened? is that something we could replicate in order markets?
2.1 What would be the ideal bisq market and what do we need to do in order to get there?

3. some competitive thinking: rumour has it that Local bitcoins will enforce all buyers to send them their passports and IDs to be stolen by a hacker at a later point in time. Is there anything in particular we can do to welcome the users who don't want to get their private data exploited by Local Btc?

3.1 with that in mind, do we have a safe way to offer first timers an on-ramp?

Well, I hope these lead to meaningful discussions and sorry if I'm brining topics back from the dead in case if they were discussed already. 

See you all on Thursday!

**Comment by m52go** [comment]
@FKrauss all great questions and ideas. We can perhaps discuss 1, as it relates to on-boarding new contributors, but I would prefer to stick to contributing as much as possible on this call. 

It might make sense for us to have a separate discussion, and then possibly make growth tactics the topic of the next call.

**Comment by ManfredKarrer** [comment]
I hope some other devs can join and maybe we can discuss a bit how we can do the onboarding and introduction for new devs.

**Comment by ripcurlx** [comment]
> I hope some other devs can join and maybe we can discuss a bit how we can do the onboarding and introduction for new devs.

I'll join as well.

**Comment by thehapax** [comment]
Hi I am new as well. Missed the the zoom meeting but are there notes or is the meeting recorded somewhere?

**Comment by m52go** [comment]
@thehapax yes, call is uploaded here:
https://www.youtube.com/watch?v=NJKldxdEnEY

Closing as complete.
