### ISSUE TITLE
Ether ETH/BTC Volume Booster Bounty 1000 $BSQ

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#177]
### Ethereum ETH/BTC Volume Booster Bounty

The goal of this bounty is to increase ETH/BTC trading volume.

To claim this bounty a contributor must outline and execute a strategy over a 3 month period to attract traders and increase volume traded in the ETH/BTC market by 50%.

https://bisq.network/markets/?currency=eth_btc

1. Declare intention to claim bounty
2. Outline strategy
3. Report on progress and detail work done here

4. **IF** volume over the 3 month period following the start of contributors work is **50% higher** than the 3 months preceding **THEN** the contributor can claim the bounty.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/72069632-e2ac5380-32e7-11ea-8228-7053cdda605d.png)

ETH/BTC is currently a tiny market for Bisq, but considering volume on other markets this could have very large potential to generate revenue if Bisq is able to capture even a small % of that flow. An effective strategy to attract such volumes would be worth a lot.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/72147879-cf5cbf00-339f-11ea-9e4b-7c390374b555.png)

ETH/BTC volumes have been small over the past 3 months:
October 2019  0.63 BTC
November 2019 0.85 BTC
December 2019 5.41 BTC

However in the past we have had much larger volumes, so the potential could be relevant. A 1000 $BSQ bounty would not be justified just by extra fees generated through a 50% volume increase... BUT the strategic value of becoming an alternative market for the largest crypto-crypto pair is significant.

Nevertheless if somebody feels the value of this bounty is not appropiate, please comment here and we can adjust it after proper discussion.

**Comment by bounhun** [comment]
I'm claiming this bounty toghether with [LTC](https://github.com/bisq-network/growth/issues/178#issuecomment-577709523) bounty.
I'm waiting for your approval to start.

**Comment by flix1** [comment]
It's great that you wish to claim this bounty @bounhun !

Please **outline your strategy** here as required in step 2. How are you going to achieve this goal?

If you start on February 1st the benchmark for success will be ETH/BTC volumes for the months of Nov-Dec-Jan.

**Comment by bounhun** [comment]
First weeks I'll try keep offers online following a similar pattern to this:
BUY 0.01 btc at -1%, 0.1 at -2.5%, 0.25 at -4% and
SELL 0.01 at +1%, 0.1  at +2.5%, 0.25 at +4%.

I'm not going to make any promotion other than a few forums where I'm already active at. I think Bisq needs volume to be appealing for traders, so I'm providing it.

I'd like to start as soon as possible, but I agree the benchmark needs to be clear for all.

**Comment by flix1** [comment]
I believe that lack of liquidity is what drives most would-be traders away. A few months of available offers plus some word of mouth can do wonders.

However I'd like a few days to give other Bisq contributors an opportunity to object, ask questions and confirm that they agree to this bounty.

**Comment by flix1** [comment]
@m52go  Can we give @bounhun the OK to start?

**Comment by m52go** [comment]
Sounds like a plan -- let's see what happens :+1:

**Comment by bounhun** [comment]
Hunting this one as well. 
Volume at end of April must be over 10.2BTC ($86.200) to claim this bounty.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/73172641-c2f89600-4103-11ea-8806-cbedf1c85d9c.png)

It's a nice start...

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/73528982-2ccfb300-4416-11ea-97ca-1e8ec2e3041a.png)

Nice to see that we are getting ETH/BTC trades almost every day since this started... The increased liquidity provided is no doubt having an effect. Hopefully it will gather momentum in february as word gets around!

**Comment by bounhun** [comment]
### Review:
I've managed to have almost 24/7 the offers published with the with the previously proposed offer structure.
There's been 8 trades performed for 0.17BTC, which is better than previously but still very little. Since a few days ago, there were some instant trade offers, that's not very convenient for me as I want to have the trades 24/7 and the alerts on my mobile phone are not working properly, but I might eventually activate some of these or pick them if I find something attractive.
All the trades performed smoothly except one selling offer that had very little mining fees and I had to resend it but didn't get to moderation and the my peer was very helpful using the trade chat.
### New offer structure
Almost all trades were for 1% and 0.01btc. I don't want to have many offers if they're not going to be taken, so I'm going to narrow spreads providing more volume at lower margins. This is the new offer structure:
0.01 BTC at 0.8% (this offer might not always be available)
0.025 BTC at 1%
0.06 BTC at 1.5%
0.1 BTC at 2.25%
0.25 at 3%
Both for buy and sell. Total volume offered will be 0.87 BTC all under 3%, and spread for buy/sell is reduced from 2 to 1.6%.

**Comment by flix1** [comment]
This looks like a very interesting iteration @bounhun 

More volume and lower spreads are obviously better for takers... My concern is that this activity should be profitable for the maker, otherwise after the bounty you will not continue...

I think that a small amount of communication in ETH trading forums could also help...

**Comment by bounhun** [comment]
0.8% offers won't be always available, this way it's more dynamic. I did not have too much hope for trading 0.25 btc at 4%, and these 10 days proved it (only one offer for 0.1 at 2.5%). I don't like having unproductive offers.

**Comment by flix1** [comment]
Nice to see that you had one of the 0.06 BTC offers taken... it would be very interesting to know more about why that one... and to see if you can replicate.

![image](https://user-images.githubusercontent.com/4233784/74442658-27d91d80-4e72-11ea-8025-8259a9b740b7.png)

**Comment by bounhun** [comment]
> Nice to see that you had one of the 0.06 BTC offers taken... it would be very interesting to know more about why that one... and to see if you can replicate.

I guess that big traders want big orders to reduce costs, because there were still available 0.01 and 0.025 orders with less spread.
I'm thinking that this is how XMR works and this is how ETH worked in the past (May 2016, mean trade was 0.57BTC and Jul 2019 13.93 BTC traded in 11 trades, a mean of 1.26BTC per trade) so I'm going to try to adjust to this situation. If I have a few thumbs up, I'll try to post a few instant trades  for 0.5 BTC or higher with a spread between 1.5 and 3%.

> If you could do one of those every day... 0.06 x 30 = 1.8 BTC ... you would be well on your way to doubling previous monthly volumes...
 
ETH orderbook now looks even better. Lots of buy offers with attractive prices. If someone other than me perform some trades, I think we'll be on the best direction -although this could be caused just by the current rally- because one guy can't and shouldn't create the whole market.

![Captura de pantalla_2020-02-14_21-13-01](https://user-images.githubusercontent.com/60184319/74564303-0ca00800-4f6f-11ea-92bf-567264f74f28.png)

**Comment by m52go** [comment]
> If I have a few thumbs up, I'll try to post a few instant trades for 0.5 BTC or higher with a spread between 1.5 and 3%.

I would say, go for it—already 17 offers with an average spread of 1%...looking like quite a solid offer book, but might benefit from some bigger trade sizes? Worth a try.

**Comment by bounhun** [comment]
**Review:**

Offers were posted with earlier proposed structure 24/7, and the results are mixed. While frequency and volume is very similar to earlier period (low, while improving pre-bounty volume) there are sell offers at very interesting prices (normally 0% spread) from other traders, but they're not taken.
There's been 5 trades performed for 0.155 BTC total, all performed by me. I took a sell ETH offer at 0.75% in my favour.
I had not any problem performing the trades, except one trade that took 3 hours to get its first confirmation and almost 24 hours to be completely settled.

**Offer structure:**

I'm trying to create bigger offers, so offer structure has slight changes and I'll try to perform over 0.3 BTC instant trades for spreads between 1.5 and 2%:

0.01 BTC at 0.8% (not always available)
0.025 BTC at 1%
0.06 BTC at 1.5%
0.1 BTC at 2.25% (decay to 1.5%)
0.25 BTC at 2.8% (decay to 2.25%)

I don't like having unproductive offers:
0.25 and 0.1 BTC offers spread will decay 0.1% points each day until they reach the upper level (2.25% for 0.25BTC offer and 1.5% for 0.1% offer).

**Comment by bounhun** [comment]
**Review**

Results for this period are good. Volume has been increased to 0.8844 BTC with 12 trades, more than 1 per day. For that increase to happen, I think it helped to have other traders performing trades between them and reducing spreads for big offers.
There were no incidents performing my trades.

**Offer structure**

BTC | Spread % 
------|-------|
0.015 | 0.80
0.03 | 1.00
0.06 | 1.5
0.1 | 1.9
0.25 | 2.3

0.6, 0.1 and 0.25 offers will reduce 0.1% their spread daily. 0.015 offers won't be always available. I might crreate temporary instant big offers to buy or sell with a spread between 1 and 2%.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/75768212-349bb380-5d44-11ea-9bc8-2ffbc3a00cd8.png)

March volumes already looking great!

**Comment by bounhun** [comment]
**Review**

Orders have been available almost 24/7. This period had 0.935 BTC for 11 trades, best volume since this bounty started. All trades in this period have been performed by me.
It's good numbers, but there's very few good orders (I consider good orders those under 2%) other than mine.
There were no trouble performing any trades.

**Offer structure**

Prices are reduced again, some of these orders are instant.

BTC | % 
------|-------|
0.015 | 0.80
0.03 | 1.00
0.06 | 1.3
0.1 | 1.6
0.25 | 1.9

0.06, 0.1 and 0.25 reduces it's price 0.1% every day until reach higher level. Special prices will be offered on Thursdays, to Make the Market March.

**Comment by bounhun** [comment]
#### Review

Orders have been available almost 24/7. This period had 0.725 BTC for 9 trades, in line with earlier period. Some trades have been performed between other users.
Still very little offers under 2% range, which are the ones that are taken often. Mining fees are high lately, and small offers like 0.01 BTC suppose a high trade % in fees, specially for takers.
There were no trouble performing any trades.

#### Offer structure

Offered orders for this period might be chaotic depending on mining fees (small offers become unattractive), but this is a reference:

BTC | % 
------|-------|
0.03 | 0.6 - 0.8
0.06 | 0.8 - 1
0.1 | 1 - 1.3
0.25 | 1.3 - 1.7

I might be offering 0.1 and 0.25 BTC orders at very low prices. Special prices will be offered on Thursdays, to Make the Market March.

**Comment by bounhun** [comment]
#### Review

Only 4 trades for 0.179 BTC. It's strange, even with this crisis, volume wasn't bad at other exchanges. I hope it gets better.

#### Offer structure

This is the last month for the bounty, I'm already making orders very close to spot or at spot. Total volume in orders should be lower.

**Comment by bounhun** [comment]
#### Review

Orders were posted almost 24/7, hack didn't affect me except for trading halt. 17 trades were made and 1.463 BTC were traded in this period, biggest and pretty acceptable overall. Most, but not all, has been conducted by me and most of them were traders selling ETH.
I wonder how much impact does have the mining fees to trading, specially for amounts under 0.02 BTC. Although very nice prices must be the main reason, last period's low trading activity might be caused by high mining fees as well.

#### Order structure

I'm keeping all of my orders under 1% spot.

**Comment by bounhun** [comment]
#### Review

This is the last period, for the bounty, but I'll try to keep orders just like now until the end of DAO cycle.
It's been another nice period, 1.51BTC traded in 15 trades. Most but not all trades have been performed by me.

#### Order structure

I'm keeping all my orders under 1% spot.

**Comment by flix1** [comment]
Looking amazing!

![image](https://user-images.githubusercontent.com/4233784/80281041-b71f6e80-8708-11ea-9f89-19758fbf83af.png)

There's a clear uptrend in daily volume here. I don't know what the strategy was, but feedback and final report should be very interesting.

**Comment by bounhun** [comment]
38 orders in the last period, for more than 4 BTC. Last week had 21 trades for 2.44 BTC, different traders are buying ETH and I think if it wasn't for me they would not find a seller. As most of the trades have been performed by me as maker, I would say that the market making is taking effect. All orders are over 0.7 % spot, so this activity is profitable on its own.
Although volume still needs to increase (bigger orders would be needed for that), April had 61 trades, the second best month since ETH is available for trading at Bisq and a change happened since the start of this bounty.

During this bounty, about 10BTC have been traded. Volume and number of transactions has increased lately, I'll maintain the orders indefinitely but I'll just make a couple more reports until the end of this DAO cycle when I'll make a compensation request for the full amount of the bounty.

@flix1 There was not a change in the strategy, other than the price structure that has been reported through this bounty. Traders want good prices and reliable service, (which includes being able to buy or sell when needed) and I'm providing that. My wish list for Bisq includes segwit -to reduce mining fees-, 2FA and a faster dispute resolution system. 
Making an order now it's cheaper and I think that's good not only for me, but for Bisq in general. The API, a more complete mobile alert system or automatically deactivate instant orders at night would be other remarkable improvements.

I think most of what I had to say have been said in prior posts, but I'm available for any questions that you think necessary.

**Comment by bounhun** [comment]
May had 23 trades for 2.808 BTC, and June 14 trades for 1.03 BTC so far.
As previous months, volume is not very high, but number of trades is good.

**Comment by flix1** [comment]
This bounty was successfully claimed.
