### ISSUE TITLE
Litecoin LTC/BTC Volume Booster Bounty 500 $BSQ

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#178]
### Litecoin LTC/BTC Volume Booster Bounty

The goal of this bounty is to increase LTC/BTC trading volume.

To claim this bounty a contributor must outline and execute a strategy over a 3 month period to attract traders and increase volume traded in the LTC/BTC market by 50%.

https://bisq.network/markets/?currency=ltc_btc

1. Declare intention to claim bounty
2. Outline strategy
3. Report on progress and detail work done here

4. **IF** volume over the 3 month period following the start of contributors work is **50% higher** than the 3 months preceding **THEN** the contributor can claim the bounty.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/72069789-4040a000-32e8-11ea-83ca-92298d99e432.png)

LTC/BTC is a very small market currently for Bisq. This bounty should be easy to win. Just attracting a handful of active traders will be enough to achieve the 50% increase in volume. 

However the lessons learned and feedback on how to do this will be very useful information to Bisq and an effective strategy could be replicated by contributors in other markets.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/72147320-8c4e1c00-339e-11ea-9316-65affbcf8071.png)

LTC/BTC volume for the last 3 months was under 1 BTC.
October 2019  0.5 BTC
November 2019 0.0 BTC
December 2019 0.3 BTC

So on the one hand a 50% increase should be very easy to achieve for whoever wants to claim the bounty. On the other hand the 500 $BSQ will probably not be justified by extra fees generated for the DAO. However I do think this is worth it as an experiment. If it works there are other markets that this could be applied to.

However if anyone feels that this bounty does not add value to the DAO I will be happy to review and change the amount of the reward.

**Comment by bounhun** [comment]
I claim the intention to collect this bounty.
I've talked to @flix1 about strategy to develop, I'll start as soon as I have got confirmation that there will be BSQ left for me at the DAO if I achieve the goal of this proposal.
I'm claiming ETH growth bounty as well.

**Comment by flix1** [comment]
Hi @bounhun you have done step 1 - announced intention to claim the bounty.

Now step 2: outline strategy...

...please **describe here your strategy** so that other DAO users can give you a thumbs up and discuss. No need to give away any secrets or too much detail, just enough so that Bisq contributors can judge that you will make a worthwhile effort.

I think we can take the ETH/BTC volumes of Nov-Dec-Jan as reference to measure the bounty's success... and you could start on February 1st.

Whatever we learn from your efforts will be very useful for future bounties, so your reporting here will be very good info for Bisq.

**Comment by bounhun** [comment]
First weeks I'll try keep offers online following a similar pattern to this:
BUY 0.01 btc at -1%, 0.1 at -2.5%, 0.25 at -4% and
SELL 0.01 at +1%, 0.1 at +2.5%, 0.25 at +4%.

I'm not going to make any promotion other than a few forums where I'm already active at. I think Bisq needs volume to be appealing for traders, so I'm providing it.

I'd like to start as soon as possible, but I agree the benchmark needs to be clear for all of us.

**Comment by flix1** [comment]
I like this strategy, I believe that lack of liquidity is what drives most would-be traders away.

However I'd like a few days to give other Bisq contributors an opportunity to object, ask questions and confirm that they agree to this bounty.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/73120525-a6c3f000-3f6f-11ea-9854-658e8477b9e3.png)

Is this you already? I have never seen a 2 BTC trade in this market before..

**Comment by bounhun** [comment]
No, I'm not. My max offer will be 0.25 btc at the beginning. I'm waiting for a clear benchmark and your OK.

**Comment by flix1** [comment]
@m52go do you have any questions about this? Can we give @bounhun the OK to start?

**Comment by m52go** [comment]
@bounhun anything in particular you're looking for with regard to benchmarks? It sound like you have a clear-enough strategy for making this market, as well as a plan to report progress. 

Otherwise this sounds like a worthy experiment to me, please go ahead.

**Comment by bounhun** [comment]
OK I start today then.
Volume from today to end of April needs to be over 3.575 btc ($30.200) to claim this bounty.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/73172452-59788780-4103-11ea-893f-97b1d03e2a7a.png)

Litecoin offer book is looking better than ever! I hope it translates into trades.

**Comment by bounhun** [comment]
### Review:

I've managed to have almost 24/7 the offers published with the with the previously proposed offer structure.
There's been 3 trades performed. Still little, but more regular than before, and as @flix1 pointed out there's other offers published and offer book looks better.
All trades were smoothly and settled fast.
### New offer structure
All trades were for 1% and 0.01btc. I don't want to have many offers if they're not going to be taken, so I'm going to narrow spreads providing more volume at lower margins. This is the new offer structure:
0.01 BTC at 0.8% (this offer might not always be available)
0.025 BTC at 1%
0.06 BTC at 1.5%
0.1 BTC at 2.25%
0.25 at 3%
Both for buy and sell. Total volume offered will be 0.87 BTC all under 3%, and spread for buy/sell is reduced from 2 to 1.6%.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/74442155-4e4a8900-4e71-11ea-86ab-d1b5c533bdd8.png)

We are definitely seeing more movement in this market since the bounty started... there's some volume done almost every day.

**Comment by MwithM** [comment]
**Review:**

Offers were posted with earlier proposed structure 24/7 and I think results are good.
There's been 6 trades performed for 0.2223 BTC total. There usually are other offers available, but the best ones are mine. Offers over 3% spread are hardly ever going to be taken unless price feed fails or other anomaly occurs. Anyhow, during this period, I did not participate in one of the trades, which is a better indicator than volume or frequency. Attract other participants that naturally interact between each other is a very good signal.
I had not any problem performing the trades.

**Offer structure**

No big changes, but big offers will be more attractive:

0.01 BTC at 0.8% (not always be available)
0.025 BTC at 1%
0.06 BTC at 1.5%
0.1 BTC at 2.25% (decay to 1.5%)
0.25 BTC at 2.8% (decay to 2.25%)

I don't like having unproductive offers:
0.25 and 0.1 BTC offers spread will decay 0.1% points each day until they reach the upper level (2.25% for 0.25BTC offer and 1.5% for 0.1% offer).

**Comment by bounhun** [comment]
Review:

Offers were posted with earlier proposed structure 24/7 and I think results are good.
There's been 6 trades performed for 0.2223 BTC total. There usually are other offers available, but the best ones are mine. Offers over 3% spread are hardly ever going to be taken unless price feed fails or other anomaly occurs. Anyhow, during this period, I did not participate in one of the trades, which is a better indicator than volume or frequency. Attract other participants that naturally interact between each other is a very good signal.
I had not any problem performing the trades.

Offer structure

No big changes, but big offers will be more attractive:

0.01 BTC at 0.8% (not always available)
0.025 BTC at 1%
0.06 BTC at 1.5%
0.1 BTC at 2.25% (decay to 1.5%)
0.25 BTC at 2.8% (decay to 2.25%)

I don't like having unproductive offers:
0.25 and 0.1 BTC offers spread will decay 0.1% points each day until they reach the upper level (2.25% for 0.25BTC offer and 1.5% for 0.1% offer).

**Comment by bounhun** [comment]
**Review**
There's been only 3 trades for 0.0639 BTC in total. I don't know how to explain this results comparing them to ETH results. Maybe is just a bad streak. There were more offers from other traders in previous periods as well.
One of the offer is in moderation because the other part has not responded and I guess I'll still have to wait for refund agent to come. This takes too many time for a simple case like mine, the other part is trying to do a future trade.

**Offer structure**

Spreads are reduced again for big offers.

BTC | Spread % 
------|-------|
0.015 | 0.80
0.03 | 1.00
0.06 | 1.5
0.1 | 1.9
0.25 | 2.3

0.6, 0.1 and 0.25 offers will reduce 0.1% their spread daily until they reach the higher level. 0.015 offers won't be always available.

**Comment by flix1** [comment]
This feedback is very much appreciated @bounhun it really helps narrow down what works and what doesn't for future initiatives...

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/75768604-f2bf3d00-5d44-11ea-9d36-4e4b589fe3c0.png)

Volumes so far..

January: 2.10 BTC
February: 0.30 BTC
March:  ....

With almost a full month to go this bounty is almost a lock!

**Comment by bounhun** [comment]
**Review**

Offers have been available almost 24/7. There's been 5 trades for 0.1618 BTC, better than last period and similar to previous ones. All trades have been performed by me. Last Thursday, there was a 2BTC order for a few hours at fixed price, for around 1% that was not taken.
I still have an order into mediation, waiting for refund agent to say something. It's a very easy dispute that should have been instantly refunded. Time for dispute resolution it's extremely large for altcoins, and the rule for max response time, which is 5 days for refund agent, is not even fulfilled. 20 days and counting with my funds blocked is simply too much, for an instant trade without any software issue.
There was an instant trade, though where mediation was performed right. The issue was that the other part took too many time to respond and I got some compensation for it.

**Offer structure**

Prices are reduced again, some of this orders might be instant.

BTC | % 
------|-------|
0.015 | 0.80
0.03 | 1.00
0.06 | 1.3
0.1 | 1.6
0.25 | 1.9

0.06, 0.1 and 0.25 reduces it's price 0.1% every day until reach higher level. Special prices will be offered on Thursdays, to Make the Market March.

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/76301939-71752680-62bf-11ea-8c7d-a19fdb3ea9f8.png)

Congratulations! Nice volume today.

**Comment by bounhun** [comment]
#### Review

Offers have been available 24/7. There's been 4 trades for 2.076 BTC. As Flix noticed, there was a trade for 2.0 BTC that someone took from me while I was hesitant to take. It was a fixed price offer with something like 0.5% premium. I wish there were more like that and I'm glad someone took it, it means market is being watched and attractive offers don't stay for long.

It's going to be a month with an offer in dispute because of future trading. The other part has been completely unresponsive, and arbitrator still made me wait for his response, and informed me that mediators don't share any info with him so everything has to be reviewed again. He told me that the other part has 3 days to answer. Since then, it's been 7 days with no answer from arbitrator, and soon will be a whole month with my funds locked in a trade without any technical issues.
It's very frustrating, disputes for altcoins can be done with 3 days for mediation since trade period expired and 4 days for arbitrator. It's strange that mediator and arbitrator aren't sharing any info, and that the other part can block your funds for such a long time just not accepting mediator suggestion. 

#### Offer structure

Orders for this period might be chaotic depending on mining fees (small offers become unattractive), but this is a reference:

BTC | % 
------|-------|
0.03 | 0.6 - 0.8
0.06 | 0.8 - 1
0.1 | 1 - 1.3
0.25 | 1.3 - 1.7

I might be offering 0.1 and 0.25 BTC orders at very low prices. Special prices will be offered on Thursdays, to Make the Market March.

**Comment by bounhun** [comment]
#### Review

Only one offer, but a big one. 0.25 BTC

#### Order structure

This is the last month for the bounty, I'm already making orders very close to spot or at spot. Total volume in orders should be lower.

**Comment by bounhun** [comment]
#### Review

Orders were there 24/7, except trading halt. There's been 12 trades for 0.509 BTC, best ever.
A considerable amount of trading has been performed between other traders.
I did not have any issues settling the trades.

#### Order structure

Keeping all orders under 1% spot.

**Comment by bounhun** [comment]
#### Review

Even with the lower prices ever, there have been just two trades for 0.12 BTC. There are other traders making orders but too expensive (+3%).

#### Order structure

Keeping all orders under 1% spot.

**Comment by flix1** [comment]
Very nice progress!

![image](https://user-images.githubusercontent.com/4233784/80280883-7115db00-8707-11ea-90f0-c02f56cb142d.png)


October 0.50
November 0
December 0.30
January 2.10
---
February 0.30
March   2.48
April (so far) 0.64

bounhun is well on his way to winning this bounty and achieving that 50% increase in volume.

**Comment by bounhun** [comment]
Just 0.04 BTC have been traded in this period, in 4 orders and most of them not mine. Very annoying considering I'm offering spreads near 0 just to remove some liquidity stuck with LTC.

About 3.4 BTC have been traded in the last 3 months. If we remove the 2BTC trade on 10th March, it's 1.4 BTC. An increase considering earlier periods, not a big one, but the proportion with ETH makes sense (last 24 hour volume for ETH is 4 times higher than LTC).

I will keep the same orders until the end of this DAO period and later it will be reduced, but my intention is to keep doing this market making as long as there's interest on this coin.

For more detailed info about the bounty, read ETH [final report](https://github.com/bisq-network/growth/issues/177#issuecomment-623528637) because conclusions are similar.

**Comment by bounhun** [comment]
May was a good month, with 13 trades for 0.951 BTC. June has 2 trades for 0.07 BTC only.
Most of them performed by me.

**Comment by bounhun** [comment]
June had four trades, for 0.18 BTC. I'm glad July ishaving good numbers (7 trades for 0.78BC) even when I stopped trading from 2nd July to 17th.

I expose on the ETH thread the reasons why I want to make the bounty request again.
