### ISSUE TITLE
Bisq growth metrics & funnels

### ISSUE THREAD

**Issue by shawnyeager** [bisq-network/growth#179]
<img width="872" alt="Bisq Growth Metrics   Funnels - January 9, 2020" src="https://user-images.githubusercontent.com/980297/72165376-fbbb1000-338c-11ea-91a6-45f6c84cc4e5.png">

Here's a v1 set of metrics and funnel(s), from conversations @m52go and I have had. Of note:

- Section 1. This is a WAG (wild-ass guess) for purposes of illustration, but the intent is to peg our growth target in BTC, as a function of trades and average trade size.
- Sections 2. and 3.: These are complete guesses, again meant to illustrate. The work to be done is to capture actual conversion #s and feed them back into the model.
- Section 4.: Our intent is not to focus on paid acquisition, and this illustrates why. Though the idea is to get more efficient, it still ain't cheap.
- Sections 5. and 6.: This is the meat of it. What levers can we pull to get users over the hump to each next stage of the funnel, and what experiments can we run to pull these levers effectively.

Please provide feedback, particularly on 5. and 6., and any resulting experiments you think we should run.

**Comment by shawnyeager** [comment]
Copying this over from @m52go on Keybase, as they're key considerations:

> as a free software project we have some disadvantages over conventional companies. among the biggest disadvantages is lack of ability to track a user from acquisition to revenue. there's a black box between what a user does on the website and what they do on the software.
>
> so i think at the moment (and maybe indefinitely) we'll need to optimize acquisition and activation (discover bisq and downlad it) separately from retention and revenue (actually use bisq to trade).

**Comment by m52go** [comment]
Thanks Shawn. I intended to respond to this thread quicker but encountered a couple of notable items that changed my approach. In a nutshell, I was going to suggest that we follow a more conventional content strategy to increase website traffic, downloads, and (ultimately) volume...but I'm not convinced we need to do all that right now. Such a full-funnel approach is something we'll need to tackle in the mid-to-long-term but isn't absolutely necessary right now.

**More important is to simply boost liquidity so that people trade more**. To me this involves increasing offers in big markets (XMR, USD, EUR, CAD) and plugging only the most glaring gaps preventing this from happening (incentives, onboarding, support). The rest (smoother website, content, etc) is stuff we should push to later. 

_The mentality we should adopt is that we're on a sinking ship and can only grab what we can hold in our hands._

To that end, I suggest the following experiments:

## Hold consistent series of liquidity days

**Objective**
Liquidity is the biggest problem with Bisq, so we should attack it head-on. Liquidity days are a proven method to do this.

**Methods**
* hold series of liquidity days for major currencies (XMR, USD, EUR, CAD)
* build on momentum from previous ones to attain higher highs...maybe make a 3-4 month "marathon" liquidity event with liquidity events every 30 days
* must be careful not to overdo it (i.e., tire the concept)

**Notes**
* takes away lots of peoples' only reason not to use Bisq in one fell swoop
* turns out the Monero market was being boosted by someone who held consistently held liquidity days in a big XMR Telegram group

**Intended result**
Directly improve liquidity in key markets by increasing available offers and overall activity.

## Make onboarding and support easier

**Objective**
Make it easier for new users to get started

**Methods**
- knowledge base: break down common issues in dead-simple how-to steps (e.g., btcpay's faqs) (in progress)
- hold online workshops to help hesitant users get their questions answered immediately...these would  just be a manual substitute for a software wizard (not something we can/should do forever)

**Notes**
- workshops may fail because many Bisq users are often technical enough to figure it out and don't need them
- but they may act as an impetus for technical people to get started, ask questions, figure out how things work without reading docs, etc
- could be a great lead-up to liquidity days
- almost no time/resource commitment, just messaging to announce and spread the word

**Intended result**
Remove barriers to being more active on Bisq

## Establish rudimentary content strategy

**Objective**
Become a more regular part of Bitcoin Twitter conversation

**Methods**
* tweet at least 1-2 soundbites per week from "pillar content" such as calls, podcasts, and talks
* broadcast 1-2 "did you know" style software tips/tricks per week (most likely from the upcoming knowledge base)
* highlight important code merges and features...there's a lot of cool stuff in release notes that users never learn about (inspired by wasabi)

**Reasoning**
* relatively low-effort and low time commitment, since there's no pressure to create original blogs and video
* this seems to be primary way projects like btcpay and wasabi get attention...they're not writing blogs or making videos, just keeping their followers very engaged with day-to-day achievements and goals
* would make bisq and what it's doing accessible for far more people, especially those who cannot take the time to read long documentation and watch long videos

**Notes**
* should still be supplemented with more significant content strategy including original blogs and videos when we have the resources
* this approach will be heavily reliant on Twitter since it's our most powerful medium, but we should also keep in mind Keybase, the forum, Telegram, and various subreddits have considerable reach as well

**Intended result**
Make Bisq top-of-mind for anyone looking to buy/sell bitcoin or monero

## Explore partnerships to create happy path for bitcoin and monero users

**Objective**
Take advantage of adjacent communities to promote Bisq

**Methods**
* determine tools useful to Bitcoin and Monero users and work out a way to recommend their tools in exchange for recommendations to use Bisq
* why? buying Bitcoin or Monero is only the first step in a journey, and piggybacking on adjacent communities' reach could be an efficient way of getting the word out about Bisq

**Notes**
* more research and guidance needed

**Intended result**
Increase awareness of Bisq to people who are highly likely to use it

## Showcase at worthwhile events

**Objective**
Engage with users and community in real life

**Methods**
* exact events to be determined, but a big showing at bitcoin 2020 is in discussion

**Notes**
* it's important to make such efforts worthwhile, i.e. that audience, medium, activities, and effect actually "move the needle"
* every opportunity is different, so must determine specific merits on case-by-case basis

**Intended result**
Spark word-of-mouth and awareness that ripples throughout digital efforts

---

There's no question we need more to happen in the mid-to-long-term to make Bisq better. But I think a razor-focus on increasing liquidity _right now_ should supercede any other intermediary goals.

For completeness, below is a listing of such goals for discussion and future consideration:
* original content strategy including 1-2 blog posts/essays and well-produced videos
* overhaul website flow, seo, etc to boost conversions (maybe minor critical changes can be made now)
* bolster documentation with Bisq inner workings, organization, infrastructure, principles, etc (wasabi is great example here)
* pilot new peer-to-peer social network like Aether (goes with Bisq's mission of decentralizing all the things, and is an unmet need of bitcoin twitter that is sure to flare up again at some point)
* explore bounties and other approaches for bootstrapping new markets (once established markets are more stable)
* create preparatory materials for meetups and other events so less preparation is needed by potential speakers
* tie software with support materials like upcoming knowledge base and documentation
* create wizard and pointers in the software for smoother onboarding, as well as to nudge inactive users to take actions
* make more effort to discover first-time user pain points (this may be achieved with n00b workshops proposed above)
* pay for spots on podcasts (probably best form of paid reach, probably not something to consider for a long time, if ever)

**Comment by m52go** [comment]
Supplanted by new growth approach detailed [here](https://github.com/orgs/bisq-network/teams/growth/discussions/1) (or [here](https://gist.github.com/m52go/4e0e5c5f8fef4d71e22ee4eaa742d141), if you can't access the first link).

With that said, there are some good ideas here that we should refer back to when the time is right. At the moment, we need to focus on liquidity.
