### ISSUE TITLE
China CNY / BTC Market Maker+ Bounty 1200 $BSQ

### ISSUE THREAD

**Issue by m52go** [bisq-network/growth#187]
### China CNY / BTC Market Maker+ Bounty

_This bounty follows the successful bounty claimed in #135. The goal of his bounty is to provide more liquidity and stronger marketing to result in more activity, possibly paving the way for [a CNY liquidity week](https://github.com/bisq-network/growth/issues/45). See [this comment](https://github.com/bisq-network/growth/issues/135#issuecomment-586807803) for more background._

To claim this bounty the contributor must make a market in Bisq CNY/BTC for 1 month.
https://bisq.network/markets/?currency=btc_cny

This will involve:

1. Keeping at least **4 BUY** and **4 SELL** offers live during 1 month.

2. Attracting other traders to the market through marketing, communication, social media.

3. Completing at least 10 trades.

4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

5. Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

**Comment by RadishXN** [comment]
I claim this bounty.
> 1. Keeping at least 4 BUY and 4 SELL offers live during 1 month.

After communication with m52go.So I only need to keep 2 BUY and 2 SELL alive.I have keep 2 BUY and 2 SELL.And so far I still keep 2 BUY and 2 SELL alive.

> 2. Attracting other traders to the market through marketing, communication, social media...

1.I have communication with the AD telegram channel onwer. And so far there have a lot of people go to bisq to sell their bitcoin. 
2.I have go to different channel to talk with different users and they would like to try bisq after my recommend. It's great we have users on bisq.
3.I try to talk with some channel onwers who have needed on sell or buy biction and I have trade with some of them.

> 3. Completing at least 10 trades.

As the picture said,I have done about 11 trades so far and I believe if possible another AD should be consider and some big players have already attract in bisq. I really hope there will be more users in bisq.
![20200411235244](https://user-images.githubusercontent.com/45912686/79048437-8c172400-7c0c-11ea-85db-26bada89bcb0.png)


> 4. Report with feedback here on the details of the trades (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

![1604cf4f0b4b5aa1](https://user-images.githubusercontent.com/45912686/79048626-efee1c80-7c0d-11ea-8bb5-3516dae5eb0a.jpg)
That's right. The trade is a litter hard. and the deposit can't be trade.
![1604cf4e80d38714](https://user-images.githubusercontent.com/45912686/79048633-f8465780-7c0d-11ea-9260-201398f35508.jpg)
It's hard to keep trade alive. without help for yours, I won't want to try it.
![1604cf4d23280368](https://user-images.githubusercontent.com/45912686/79048646-05fbdd00-7c0e-11ea-91f0-45417e28139b.jpg)
Deposit can't be traded , hoping to find a way.
And the deposit is high at some point, so I won't do a large amount trade.
![1604cf4c6391d40c](https://user-images.githubusercontent.com/45912686/79048876-8c64ee80-7c0f-11ea-91fe-7ec1627e3d41.jpg)
Exactly.
needing a sever,or keeping computer online.
it's a little inconvenient.
![1604cf4af278e90e](https://user-images.githubusercontent.com/45912686/79048880-97b81a00-7c0f-11ea-8b9e-7e1e6dcea93b.jpg)
the market doesn't big enough, deposit is a problem.
Knowing by few people is a problem.

I have got the feedback from some of the users of bisq. And bisq has already done great so far, but the problem is that it isn't convenient enough for some users in China. mobile app will be a stronge 
offset to this kind of problems. Some users also said that they love bisq and the reason can be listed as follow.
1. Privacy. Bisq has done a great jobs in privacy. They felt absolutely safe while using bisq to trade and I must say that I am glad to see that.
2. Translation & Guide. I try to teach them as much as I can and I received a really great feedback on guide them. It's great! With the Chinese translation it will help them to get trade more easily, they are pretty pleased by the translation.
That's all about the feedback part.

> 5. Attend at least 1 live Bisq Growth call to answer questions and provide feedback on the experience.

I have got a call before.And if needed I would like to have another one.

Thank you.

**Comment by m52go** [comment]
@RadishXN shared some good feedback during this call:
https://youtu.be/AxyByjMnphU

We're discussing how a future effort could look.
