### ISSUE TITLE
BOLETO as payment method for brazilian currency real (BRL) transactions

### ISSUE THREAD

**Issue by smcama** [bisq-network/growth#199]
### Why

Boleto bancário (or simply "Boleto") is the most popular payment method in Brazil. Bills in Brazil usually are payed using this method (more than bank deposits or wires). It is a barcode that you can pay with cash at banks, supermarkets, lottery agents and even some retail stores. You can also pay with your brazilian internet banking. It preserves the buyer privacy if he wants it. He just need to pay it with cash.

### Region

Brazil. Anyone with a brazilian real bank account, even not a resident, can pay or receive a boleto. Even some brazillian internet banks accept it as a deposit/funding method.

### Chargeback risk

There is no chargeback risk. Once you payed a boleto your money is gone.

### Data requirements

With bank name, payer full name and brazilian address (could be informed with the payee information with no issues), payee full name and brazilian itin (CPF)/CNPJ), amount and date due it is generate a barcode that should be informed to the payer. In a more sofisticated version, Bisq could read the barcode and turn into a pdf like it is usual to make it easy to people understand what they are paying and to who. Even so, with the barcode, the teller can give all the information or at the internet banking all the information come after inserting the barcode.
 
### Verification

After 1 business day a payed boleto will be credited at the payee account automatically with no chance of chargeback. You just need to check your bank statement next day after banks are opened.

### Duration

Boletos are cleared only monday to friday (business days).  Worst scenario is a Bisq transaction starting friday night, the buyer pay it monday (because he can't pay it saturday or sunday) and the seller need to wait until tuesday to check if he got the money. I guess giving 7 days would avoid most worst scenario situations. I would recommend it to be automatically made with a due date 2 days after it starts (you can pay it the same day or up to 2 days later).

### Fees

Some banks, fintechs and financial companies charge small fees to create boletos for you (usually less than $3), but they are not expensive and also in some internet banks boleto generation is a free service.

### Fraud risk

If you use the barcode the seller sended you and check it there is no chance of fraud. If the boleto doesn't match with the seller data (Name, amount, etc) simple don't pay it and ask for mediation.

**Comment by m52go** [comment]
This sounds quite good...I wonder why it wasn't suggested before. So with just a barcode, a buyer can get the seller's bank name, full name, and enough account information that they can cross-reference with the Bisq payment account to make a payment?

Do you know if people might already be using this method to settle national bank transfers at the moment?

@bisq-knight are you aware of this?

**Comment by smcama** [comment]
I search for it not once, but twice, before posting. Lol. It is like zelle
was not an option because nobody suggested it.

Exactly... and with a little coding Bisq could possible create it is own
boletos with the tradeid, but I think we should start the simple way: a
field where the buyer copy and paste the barcode (numbers only, don't allow
links or words) and the few information I told you need in order to confirm
the code will send the money to right person and account (someone can for
example try to put a code that goes to a different account, so the buyer
must check the boleto before paying - but even a brazilian teenager knows
that and we always check - exactly because we know there is no chargeback
in boletos).

I'm available to help this project and every new project related to the
brazilian market. For instance, Brazil is starting it is own zelle type
payment that will be called PIX by the end of the year.

**Comment by m52go** [comment]
I was really hoping for more feedback from someone more familiar with the market (@bisq-knight) but...I guess that's not happening.

Let's proceed and try to get Boleto into the next Bisq release.

Hopefully not too many questions...just need to know details to implement in code and inform mediators for handling disputes.

#### Payment account fields

Exactly what fields would be required for a user to create a new Boleto payment account in Bisq? 

From your description, it seems the following is necessary:
* bank name
* full name
* street address

Are these 3 fields enough for a seller to create a barcode? Likewise, are these 3 fields enough for the buyer to verify the barcode isn't fraudulent?

#### Cash & Chargebacks

Is it possible to make a Boleto payment with anything other than cash? Bank/debit card, credit card, etc? You mentioned cash only, but I just want to be sure, since you can also pay a Boleto electronically with internet banking.

Are you sure there's no chargeback risk? What about cases of fraud? If a buyer claims they were defrauded to their bank, can the bank take any steps to get the money back from the other back?

I saw somewhere that a Boleto can be paid after the due date at the receiving bank. Is this accurate? Does it happen a lot? I guess your suggestion for a 7-day window includes a good amount of leeway anyway.

#### Verifying

Do Boleto payments show in bank statements? Is there any other way a buyer can prove they made the payment, and that a seller can prove they received a payment? Does seller receive any kind of email or receipt upon generating the Boleto? Does buyer receive receipt from teller/cashier?

#### Signing

If there is indeed no chargeback risk, Boleto should not require [signing](https://bisq.wiki/Account_limits#Account_signing) for buying or selling.

What should limits be? Is there any limit on how big a Boleto can be?

**Comment by m52go** [comment]
@smcama I got feedback elsewhere that people might be hesitant to use Boleto as it tends to be seen as some kind of an invoice for a product/service, so sellers are likely to get a lot of scrutiny when using it.

Have you encountered this?

**Comment by ulisses1979** [comment]
There is a 10000 BRL limit for boleto payment in Cash

**Comment by Ben10Brasileiro** [comment]
Pros: Payment option

Cons: Address in the boleto, the seller need to generate the boleto.

**Comment by m52go** [comment]
Closing as stalled as concerns in previous comments ([one](https://github.com/bisq-network/growth/issues/199#issuecomment-717711875), [two](https://github.com/bisq-network/growth/issues/199#issuecomment-719000746)) haven't been addressed.
