### ISSUE TITLE
Add Tikkie as a new payment method (popular in The Netherlands)

### ISSUE THREAD

**Issue by pazza83** [bisq-network/growth#247]
## Tikkie 

Resources: 

[Tikkie website](https://www.tikkie.me/) 
[Tikkie Google Play](https://play.google.com/store/apps/details?id=com.abnamro.nl.tikkie&hl=en_GB&gl=US)
[Tikkie App Store](https://apps.apple.com/nl/app/tikkie/id1112935685?l=en)
[Tikke ABN Amro](https://developer.abnamro.com/api-products/tikkie)
[Tikke FAQs](https://www.tikkie.me/bedrijven/veelgestelde-vragen)
[Tikke YouTube](https://www.youtube.com/channel/UCARJraDYPW_rGEdv_hO15aQ)

Tikkie is a mobile payment provider service based in The Netherlands. Tikkie is developed by ABN Amro and allows anyone based on The Netherlands, and with a bank account in The Netherlands to access Tikkie. 

Tikkie is an online payment app that allows you to forward payment requests to people via WhatsApp, or pay through a QR code. Once you open the request or scan the code, you’ll be asked to forward the money through your online banking. 

### Region

The Netherlands. You need is a bank account (IBAN) in The Netherlands, and also to be based in The Netherlands.

AFAIK Tikkie is not available to users outside The Netherlands, even if they have an NL IBAN.

### Currencies

EUR

### Chargeback risk

Low

### Size of user base

5 million+ users
Over 200,000 Tikkie sent per day
38% settled within 5 mins.

### Data requirements

The service allows payments between users though either WhatsApp or sending a QR code. 

From a privacy perspective it might be best for users to send a link to the QR code via Bisq trader chat. This would eliminate any need for providing other data eg phone / email.

### Verification

TLSNotary may be used as payment method is bank based. App only banks will require screen recording / screenshots for payment proof.

### Duration

Payment link is sent. When user makes payment it is instant.

### Fees

Subscription fee is €5,00 per month to make Tikkiw payment requests. This includes 20 Tikkies. After that is is 0.25 Euro per Tikkie.
 
### Fraud risk

Low

### Payment amounts

When you send a Tikkie to several people, you can request a maximum of € 2500 euros at the same time . Per individual person you can receive a maximum of € 750 per Tikkie request.

The maximum amount within 24 hours is also € 2500 per Tikkie account. The total amount in one day may not exceed this, otherwise the payment will be refused.

Each bank however may establish its own limits, within these limits, for its clients.

**Comment by pazza83** [comment]
Hi @pingiun I would be grateful if you can give me feedback on the above.

Particularly if we can just have  users send a link to the QR payment request via Bisq trader chat?

Also not 100% on fees. Do you pay 5 Euro a month to access the service?

**Comment by pazza83** [comment]
Tikkie has been scored for inclusion to Bisq:


| Essential   | Desirable | Definite No’s |
| ------------------- | ------------------- | ------------------- |
| **Very low risk of chargeback**  | ~~No risk of chargeback~~  | ~~< very low risk of chargeback~~  |
| **Way to verify the sender in the received payment** | ~~Way to verify the sender in the received payment and ability to enter a reference~~  | ~~No way to verify the sender in the received payment~~  |
| ~~Trade time less than one week~~ | **Instant payment**  | ~~Trade time more than one week~~  |
| **Singular Fiat currency**  | ~~Multi-currency~~  | ~~Not a payment method for fiat currency~~  |
| **Significant user base** | ~~Large user base~~  | ~~No significant user base~~  |
| ~~High usability~~  | **High usability and great user experience**  | **< high amount usability~~  |
| ~~No KYC required for sending and receiving payments~~ | **No KYC required for sending and receiving payments, allows users to trade with upmost privacy. Minimal identifying information as possible (no names, email, phone etc required)** | ~~Some KYC required (proof of address, ID, selfie) for sending and receiving payments~~  |
| **Low risk of scam attempts**  | ~~Very low risk of scam attempts~~  | ~~< low risk of scam attempts~~ |
| ~~Traders can provide evidence of payment / receipt~~  | **Traders can provide evidence of payment / receipt and Verification of payment can be made using PageSigner or similar** | ~~Traders will be unable to provide evidence of payment / receipt~~  |
| ~~Minimum limit at least equal to at least account limits protocols~~  | **No minimum limits**  | ~~Minimum limit not able to achieve account limits protocols~~  |
| **Maximum limits equal to at least 0.01 BTC**  | ~~Large payment limits up to 2 BTC~~  | ~~Maximum limit is less than 0.01 BTC~~  |
| **Likely to increase liquidity**  | ~~Likely to increase liquidity and open markets for different countries and currencies~~  | ~~Likely to decrease liquidity~~  |
| **Low risk of mediation**  | ~~Very low risk of mediation~~  | ~~< low risk of mediation~~  |
| **Low risk for traders from government agencies**  | ~~No risk for traders from government agencies~~ | ~~< low risk for traders from government agencies~~  |
| **Fees should not be a barrier to trading**  | ~~No fees for transactions~~ | ~~Fees will be a barrier to trading~~  |
| ~~Only minor changes needed to trade protocol~~  | **No changes needed to trade protocol**  | ~~> Minor changes needed to trade protocol~~  |

Score: 22/32
Percentage: 68.75%

**Comment by pazza83** [comment]
### Tikkie - Proposed National Currency Payment Method 

I am proposing that Tikkie to be added as a national currency payment method.

@refund-agent2, @huey735, @leo816 please let me know if you have any questions as to how Tikkie will be mediated / arbitrated. If you have any objection please let me know by 31 May 2021.

---


Date proposal being made: 03.05.21
Date feedback to be provided by: 01.05.21

Name of payment method: Tikkie

Required fields (eg)
None? Maybe to avoid fraud users should enter the IBAN their Tikkie is linked to?

Maximum trade duration: 24 hours

Signing required: No

Regions accepted: The Netherlands

Currencies accepted: EUR

Bisq Limits: 0.05 BTC

Any relevant information for mediators / arbitrators: Verification might be via mobile screen recording if bank is app based. 

Any relevant information for devs: No

Any relevant information for users: Account limits 2500 Euros per day, 750 Euros per transaction

Screenshot of expected GUI: TBC

**Comment by pingiun** [comment]
> Hi @pingiun I would be grateful if you can give me feedback on the above.

Of course

> Particularly if we can just have users send a link to the QR payment request via Bisq trader chat?

The Tikkie app doesn't use QR codes itself. By default it presents you with the option to share a message with link via WhatsApp because this is the most used messaging system in the Netherlands. However it also has the regular share menu on Android or iOS which allows you to copy the message. Then they have to send it to the computer they run Bisq on in some way. The message includes something like "Please pay me for 'payment reference'" and includes a link to the Tikkie website.

The Tikkie website in turn refers you to your bank to make an iDEAL payment. The iDEAL payment may include a QR code (depending on their bank), but that is not relevant for Bisq, users will be familiar with this as it's just how we do web payments.

To clarify, only the website url Tikkie gives you is needed to make the payment.

> Also not 100% on fees. Do you pay 5 Euro a month to access the service?

No fees are needed. Tikkie is a free service for non-commercial use. As long as Bisq users just use Tikkie like normally on their phone they don't need to pay fees. I have no experience with the commercial features of Tikkie, but along with the fees I imagine they require a commercial bank account and a company registration (and VAT code

<hr>

[My screenshots](https://github.com/bisq-network/proposals/issues/244#issuecomment-824989070) and walk through the process from the previous issue might come in handy for implementors or arbitrators/mediators. I can also make more screenshots if desired.

**Comment by pazza83** [comment]
Hi @pingiun thanks for all the info.

I would be in favour then of not including contact number. Users can send their payment link to the BTC buyer for payment. This seems preferable in terms of privacy.

In the event of a dispute however what can be provided by way of proof.

For example.

Alice offers on Bisq 0.01 BTC using Tikkie for €500.
Bob takes offer.
Alice sends Bob a payment link.
Bob sends €500 to his friend.
Alice opens a dispute
Bob says I sent the €500

or 

Alice offers on Bisq 0.01 BTC using Tikkie for €500.
Bob takes offer.
Alice sends Bob a payment link.
Bob sends €500 to his Alice using the payment link.
Alice opens a dispute to say she never received the €500 
Bob says I sent the €500

What information can be provided in the Bisq payment method account to prove the source and origin of the funds. Would IBAN be ok? Is the Tikkie payment linked to an IBAN that both users can see?

**Comment by pingiun** [comment]
On Alice's point of view, she can show that the Tikkie item she made has not been paid for yet. In the below two screenshots you can see what this looks like:

![IMAGE 2021-05-06 09:48:49](https://user-images.githubusercontent.com/1576660/117261265-4305c380-ae50-11eb-8572-b6b496337bbd.jpg)

Here you can see the list of Tikkie items I created. The top item labeled 'Bisq' shows that the request is still open. The two items below that show how many people paid for this. Paid 6 times and 5 times respectively.

When I click on the top item you get this view:

![IMAGE 2021-05-06 09:50:16](https://user-images.githubusercontent.com/1576660/117261478-76485280-ae50-11eb-9489-8208647ec712.jpg)

It reads "Er is nog geen betaling bevestigd" which means "no payment has been confirmed yet". 

However for these two screenshots it would be possible to delete the original item that has been paid and create a new one that has not been paid yet. So to proof lack of payment, a screen recording would be needed where the receiver clicks the QR code button (in the bottom of the second screenshot). The link could also be shown, but I think this is too much hassle as it requires the user to use the share action to a place where the link is visible in the video. This QR code would then have to decode into the originally sent URL.

The QR code screen for reference:
![IMAGE 2021-05-06 09:57:08](https://user-images.githubusercontent.com/1576660/117262340-6bda8880-ae51-11eb-8d22-d26e54d3e506.jpg)

This code decodes to just the payment link: https://tikkie.me/pay/kpg0efpt6ht28f7v2jsp

<hr>

From Bob's point of view, a bank transcript is needed. For this I made a Tikkie and paid it myself. My banking app shows this for the transaction information:

![IMAGE 2021-05-06 10:05:39](https://user-images.githubusercontent.com/1576660/117263496-9d078880-ae52-11eb-9eca-229dd4680f3a.jpg)

As you can see the payment is to Abn Amro Bank Nv (the parent company of Tikkie). This is because the actual payment is done via iDEAL on the Tikkie website. However, they always includes the Tikkie description and receiving IBAN and name into the payment reference. (Shown at "Omschrijving") I blacked out part of my IBAN in this screenshot, but this can clearly be used to proof payment if the IBAN is saved into Bisq. 

Allice will also be able to see the sending IBAN on her end in the same way. For reference, here is how it would look for Alice (showing +€5,00):

![IMAGE 2021-05-06 10:09:05](https://user-images.githubusercontent.com/1576660/117263992-17380d00-ae53-11eb-9b0f-ff691106b087.jpg)

I see an issue here because some bank apps don't allow screenshots on Android. In that case a desktop could be used show the bank transcript, but on desktop it's easier to doctor webpages of course.

**Comment by pazza83** [comment]
@pingiun thanks again for all the useful info.

I think including IBAN in the payment account should solve the problem of proof.

If a website proof is needed then [pagesigner](https://tlsnotary.org/pagesigner.html)can be used.

Many thanks for the detailed screenshots. Is it ok to include them when I am creating the wiki?

**Comment by pazza83** [comment]
Here is the XD for Tikkie, it should be straight forward to add:

![Payment method - Tikkie](https://user-images.githubusercontent.com/66367547/117579170-a2cacb80-b0e9-11eb-90ec-fcf223c87910.png)

**Comment by pingiun** [comment]
> Is it ok to include them when I am creating the wiki?

That is fine, I would appreciate it if you could anonymize them.

**Comment by pazza83** [comment]
Thanks, will do

**Comment by pazza83** [comment]
## Information required for Bisq software strings:

Hi @jmacxx here is the information for the strings. 

Let me know if you need anything else:

### Special info about any of the inputs required for creating the payment account:

To use Tikkie you need a bank account (IBAN) in The Netherlands and to be registered for the service. 

When you send a Tikkie payment request to an individual person you can ask to receive a maximum of €750 per Tikkie request. The maximum amount you can request within 24 hours is €2,500 per Tikkie account. 

Each bank however may establish its own limits, within these limits, for its clients.

Traders on Bisq should be aware of their limits. If you trade over the above limits your trade might be cancelled and there could be a penalty.

### Special items to be aware about when sending payments (for BTC Buyers):

Please request a payment link from the BTC Seller in trader chat. Once the BTC Seller has sent you a payment link that matches the correct amount for the trade please proceed to payment.

When the BTC Seller requests a Tikkie payment the maximum they can ask to receive is €750 per Tikkie request. If the trade is over that amount the BTC Seller will have to sent multiple requests to total the trade amount. The maximum you can request in a day is €2,500.

Each bank however may establish its own limits, within these limits, for its clients.

Traders on Bisq should be aware of their limits. If you trade over the above limits your trade might be cancelled and there could be a penalty.

### Special items to be aware about when receiving payments (for BTC Sellers):

Please send a payment request a payment link to the BTC Seller in trader chat. Once the BTC Buyer has sent you payment please check their IBAN detail match the details they have in Bisq.

When the BTC Seller requests a Tikkie payment the maximum they can ask to receive is €750 per Tikkie request. If the trade is over that amount the BTC Seller will have to sent multiple requests to total the trade amount. The maximum you can request in a day is €2,500.

Each bank however may establish its own limits, within these limits, for its clients.

Traders on Bisq should be aware of their limits. If you trade over the above limits your trade might be cancelled and there could be a penalty.

**Comment by jmacxx** [comment]
![image](https://user-images.githubusercontent.com/47253594/140648180-2dfefef1-0d6e-42da-bb8f-19c88cbd3af0.png)


There are two places in the trade process that we typically show a popup:

- At the make / take offer stage before committing to the details.
- At the pay / receive stage of the trade, after deposit confirmation.

The problem I have with this block of text, is that if shown at make/take offer stage, it can confuse the user since it appears to be instructing the user: "_Please send a payment link..._" which is not even possible.  If it is shown at the pay/receive stage of a trade, the other information about "_be aware of bank limits_" is moot.


Ideally, if the payment link information could be worded in such a way as to indicate that it applies in the future, as opposed to right now it would make sense to display at the make/take offer stage which is typically where these popups have been placed.

@m52go WDYT?

I suppose it would also be possible to split the information, some displayed at make/take and the other displayed at pay/receive.  :disappointed:   That would introduce extra complexity to the workflow (from a dev/maintenance perspective).

**Comment by m52go** [comment]
Strictly speaking, the text can be made to work (see below). But I'm not sure it is ideal for users, since this 1 small box covers 2 distinct bits of information (sending link + limits). Two boxes would be ideal. Given the extra complexity, maybe it can be considered if the payment method sees strong usage.

For 1 box:

```
BTC seller will need to send BTC buyer a payment link in trader chat (this will be possible as soon as the deposit tx confirms). BTC seller should check that the BTC buyer's IBAN matches the one specified in Bisq.

When the BTC seller requests...
```
