### ISSUE TITLE
Complete the 1st trade in ARS/BTC

### ISSUE THREAD

**Issue by flix1** [bisq-network/growth#26]
Complete the first Bisq trade in Argentinian Pesos (ARS/BTC) and report back with 3 lines of feedback here on the details of the trade (payment method used, problems encountered, suggestions for improvement, fees paid, time it took to complete the trade).

**Bounty: 50 $BSQ**

**Comment by fedegrc** [comment]
I participated in the first ARS/BTC trade :)

Details of the trade:

- payment method used: National bank transfer (buyer and seller had different banks)
- problems encountered: No problems
- suggestions for improvement: No improvement needed
- fees paid:
  - Trading fee: 0.5% of trade amount
  - Total mining fees: 0.96% of trade amount
  - ARS fees: 0%
- time it took to complete the trade: The trade took 16hs. I'm almost sure that the ARS arrived to the seller one hour after the trade started. The seller take about 15hs to confirm that the payment had arrived. I think that the problem was that I transfer the money at night (0:50am) and the seller couldn't see it.

**Comment by fedegrc** [comment]
BSQ requested: 50
BSQ address: B1961fVVFMnQunrKVtWVsBsReLvL6q6VT3R

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/45917840-ec554200-be7d-11e8-99d3-104e8b836c11.png)

**Comment by flix1** [comment]
Congratulations @fedegrc. Well done on claiming this bounty!

What can we do next to help the ARS/BTC market grow? Are you in any forum, community of bitcoiners in Argentina where we could try to organize a Bisq day?

**Comment by fedegrc** [comment]
I'm not in any forum. I'll start with reddit.

**Comment by fedegrc** [comment]
![screenshot_20180928_083414](https://user-images.githubusercontent.com/14953828/46191866-601da180-c2f9-11e8-8b62-69af38c2ad8f.png)

**Comment by ManfredKarrer** [comment]
Great to see Argentina arriving at Bisq!!!! With the currently difficult situation there it would be really essential for people there to get into BTC with a proper privacy protecting gateway.

**Comment by ripcurlx** [comment]
Closing as complete.

**Comment by fedegrc** [comment]
@flix1, I'm not seeing in my wallet the 50 BSQs that I claimed as bounty for this first trade. Additionally, I haven't found my BSQ address in the "BSQ stake and vote tracking" doc. How should I proceed?

**Comment by fedegrc** [comment]
@flix1, I made a compensation request on October 23 following the document "Requesting Compensation and Voting".
I've just realized that I received 50 BSQ on Sep 11, the same day you reply to my question.
![Screenshot_20191029_234934](https://user-images.githubusercontent.com/14953828/67825664-d1a1c380-faa8-11e9-9a6f-f9f226b4f48d.png)

So, I think I should cancel the compensation request, could you please confirm? Thank you and sorry for the mistake.

**Comment by flix1** [comment]
@fedegrc don't cancel the compensation request. I also sent you 50 BSQ myself as a reward, but that was a personal gift, you are still due compensation from the DAO.
