### ISSUE TITLE
Launch Bisq on producthunt.com

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#31]
As ProductHunt has a very tech-savy and investment interested audience we could think about launching Bisq there as soon as the Bisq DAO is ready.

**Comment by cbeams** [comment]
+1. I pay fairly close attention to Product Hunt as well, and have thought about launching Bisq there too. I think you're right that it's too early right now (for a few reasons), but I'd like to seriously consider it at some point in the post-phase zero future.

**Comment by FKrauss** [comment]
shall we revive this talk?

**Comment by m52go** [comment]
Personally I don't think the Product Hunt crowd is a good fit for Bisq, especially at the moment.

1. I don't see any of the major commercial/company-backed bitcoin products on there—no wallets, nothing from Blockstream, etc. The only item I recognized from a search for "bitcoin" was Andreas' _Mastering Bitcoin_ book, and even that didn't generate much interest. To me, this isn't a good first sign.

2. The Product Hunt crowd (much like the Hacker News crowd) seems to be very skeptical of Bitcoin in general. My hunch is that even excellent products with excellent presentation will be met with hesitation...which is probably why no major Bitcoin project has bothered to post there yet.

3. Even assuming Bisq happens to attract lots of attention on Product Hunt (which I hear is a crapshoot even for good projects that fit well with the crowd)...is that a demographic we want at the moment? Onboarding is rough, support is a work in progress, etc.

Normally it would be no big deal to just post and see what happens, but Product Hunt has limitations on re-submitting the same site/product, so we should make sure a post there is well-considered (if it is to be done) because options for a do-over are limited:

> Product updates must be substantial, such as the launch of a mobile app or complete product redesign with new functionality, to be considered for resubmission. There also needs to typically 6 months in between postings.

https://help.producthunt.com/en/articles/484934-may-i-post-updates-for-things-previously-submitted

**Comment by FKrauss** [comment]
Sounds good. Let's put it back in the fridge

**Comment by FKrauss** [comment]
btw, shall we close some of these? This one in particular. We sort of decided we won't do this any time soon, no need to pollute our other issues that might actually have actions we may take

**Comment by pedromvpg** [comment]
We need more upvotes!

https://www.producthunt.com/posts/bisq
