### ISSUE TITLE
Launch a twitter hash tag campaign

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#32]
We could think about using a specific hash tag (e.g. #beyourownexchange) on all personal and Bisq tweets to raise awareness around decentralized exchanges. Maybe even get other exchanges on board to use it as well?.

Example:
 ````
You don't like centralized #exchanges and their downsides! Then just stop using them and support #decentralized ones! #beyourownexchange
````

**Comment by cbeams** [comment]
#BeYourOwnExchange is perhaps interesting, but I usually find hashtags like this to be gimmicky. Not always, but usually. I tend to use them very sparingly.

As for hashtags like `#decentralized` and `#exchange`, I think they're not just useless (because I don't think anyone is actually clicking on them / searching by them) but actually a negative: using hashtags in this manner always reads to me as slightly desperate.

Really good tweets take off on the merits of their content. I think it's better to obsess about crafting quality content than it is to try to take advantage of hashtags, which most people—especially developers and those in the know with crypto—see right though as transparent attempts to get more engagement.

With that said, I'm not exactly _against_ the idea of a `#BeYourOwnExchange` "campaign", but I'm only lukewarm to it. If the rest of the tweet is compelling and `#BeYourOwnExchange` is used like a tagline, it could be great.

So don't take this as throwing too much cold water on the idea—I'm just expressing my own standards for the Tweets I'm crafting and sending from @bisq_network, which also apply to what I'm likely to want to retweet from that account.

**Comment by ripcurlx** [comment]
No offense taken :-). Regarding using hashtags within the the post, I have no strong opinion, as I just started using twitter more over the last couple of months and I wanted to see if the hashtags discoverability is as effective as on instagram. I also agree that quality of posts is the most important thing to focus on. So the idea was just to use some hashtag people and other decentralized exchanges could re-use to give this topic more visibility. Still I didn't looked into more detail how much volume would be needed to break into trending topics, which could lead to more attention in general.

**Comment by m52go** [comment]
Generally speaking hashtags have become the domain of the #DeFi crowd. Every now and then it makes sense to use hashtags, but I'm going to close this issue as it's more of an ongoing/opportunistic thing that doesn't really need an issue.
