### ISSUE TITLE
2017.12.06 growth call

### ISSUE THREAD

**Issue by cbeams** [bisq-network/growth#5]
- **Date:** Wed Dec 6th 
 - **Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
 - **Place:** Zoom conferencing, see Call Details below

If you want to help Bisq grow, then this is the meeting to attend!

Everyone is welcome, and there's no need to RSVP or register, but if you do plan to attend, **please add a 👍 below** so we have an idea how many people will be there.

Note also that you can subscribe to the Bisq DAO Google Calendar to get notifications about this call and other Bisq events. See https://bisq.network/calendar.

## Agenda

A detailed agenda for the meeting will follow soon, but in general, we want to focus this call on **ways to grow liquidity**. Before we can grow the number of overall traders on the Bisq network, we first need to make sure that we have plenty of liquidity available in major trading pairs, esp. EUR and USD.

This means that anyone who considers themselves a potential 'market maker' or 'liquidity provider' is especially welcome on this call, to help us brainstorm ways to make Bisq an attractive place to be for you. We already have a number of ideas, and are looking to get your feedback.

Note that while we're happy to have pro and semi-pro traders serve as liquidity providers, we're also looking for anyone who simply has a need to sell BTC on a regular basis, e.g. for basic cash flow purposes.

## Call details

Join from PC, Mac, Linux, iOS or Android here: https://zoom.us/j/396924233 

Or join with a touch on the iPhone : 
    US: +16699006833,,396924233# or +16468769923,,396924233# 
Or join by phone： 
    Dial in： 
        US: +1 669 900 6833 or +1 646 876 9923 
    Meeting-ID: 396 924 233 
   International numbers available: https://zoom.us/zoomconference?m=SkbJ7b_Cp-8bt-nmH0Z0PX3t7jnICnUn 

## Comments welcome

Please add comments below with any questions you have or regarding any other topics you'd like to discuss on this call. See also the open issues in this repository.

We'll put everything together into a detailed agenda prior to the call. Hope to see you there!

**Comment by ripcurlx** [comment]
## Pre Meeting Expectations
As this meeting is the first of its kind, the agenda will differ from how it will be in the future. This meeting will be all about ideas to **grow liquidity**. As our growth meetings will only run for 45 minutes we'll have to do everything to make them as efficient as possible. Please take your time to go through following list before the meeting:

- Look at existing experiments by filtering for the [`liquidity`](https://github.com/bisq-network/growth/issues?q=is%3Aissue+is%3Aopen+label%3Aliquidity) label so you have a good understanding on the possible experiments being ran.
- Checkout our [monthly report](https://github.com/bisq-network/roles/issues/40) or even better, make yourself familiar with our [reporting sheet](https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing) to understand what the latest numbers are.

**Comment by ripcurlx** [comment]
## Agenda

**10 min:** Short introduction on the topic of this meeting: **Grow Liquidity** and on future structure of Growth Meetings
**10 min:** Depending on the number of participants short introduction round
**25 min:** Select tests/experiment for this week. Talk about how we handle assigning of tasks, roles and compensation

**Comment by csacher** [comment]
## Log for Growth Call #1

Join the log of the upcoming call: 
https://docs.google.com/document/d/19gMJKJa1oJ3UURqOTAOva5EglUr-7AQOluf1IQZ_ZWE/edit?usp=sharing

**Comment by csacher** [comment]
# **Bisq** - Growth Call #1

**Date:** Wed Dec 6th
**Time:** 11:15a–12:15p Pacific / 8:15p–9:15p Central European
**Place:**   Zoom
**Recordings:** [Part 1](https://www.dropbox.com/s/z1yu8l7nq699ldm/growth-call-%231-part1.mp4?dl=0) and [Part 2](https://www.dropbox.com/s/8m03dj75ik5wi7f/growth-call-%231-part2.mp4?dl=0)

**Joined By:** ripcurlx, cbeams, csacher, flix1, Manfred Karrer, Stephan Emzy, Mike Rosseel, sqrrm, Mats-Erik Pistol, MartinM, Joe, kylo

**Main Question:** What can we do in order to grow liquidity on the Bisq exchange?

**Desired Outcome of this Call:** Actionable roadmap and responsibility distribution

**@flix1&#39;s proposed liquidity targets:**

- --20 offers per given trading pair (10 Buy / 10 Sell)
- --Low spread (&lt;3%) 
- --High depth (&gt; 5 BTC)

Potential [liquidity](https://github.com/bisq-network/growth/issues?q=is%3Aissue+is%3Aopen+label%3Aliquidity) growth experiments:

1. Reach out to experienced traders on LocalBitcoins ( [#7](https://github.com/bisq-network/growth/issues/7))
2. Put together video tutorials  ( [#4](https://github.com/bisq-network/growth/issues/4))
3. Provide an easy to copy example/guide on how to use our trading API ( [#6](https://github.com/bisq-network/growth/issues/6))

---------------------------------

**Learnings**

- Instant SEPA would help a lot for EUR pairs 
- Much Higher volume in EUR than US
- Bisq needs to add more and improve the existing payment methods
- Adding payment methods is not complicated for us, just the research has to be done.
- Low trust at the beginning - people will test the application with small amounts first before transferring bigger amounts
- People want to see small spreads and small amounts in the order book (for testing the app)
- People don&#39;t get the value of decentralized exchange until one of the centralized exchange crashes.
- Users will compare Bisq to Localbitcoins (mainly prices)
- Localbitcoins.com has relatively high spreads, compared to Bisq
- Big traders have to be able to buy 20 BTC a day (Bisq is currently not providing this volume)
- At the moment people come to our exchange and see they can&#39;t buy/sell in USD, CHF and many other national currencies
- Main success factors: Trading pairs, speed of transaction, price (spread)
- We need a steep order book, minimum of 5 BTC → little price variation
- For small trades, the fees are too high (0.2%), minimum 0.001BTC
- Bisq has to be competitive with Localbitcoins.com!
- Core of the Industry still does not know Bisq - would be an easy target
- Bisq needs the pro traders because they are there every day (it&#39;s their business to trade) → they will be the ones who fill the order book and provide liquidity
- Triangular scams are very common on Localbitcoins.com and are very difficult on Bisq
- Holdhold will start with zero fees when they go live on mainnet

---> [Next step is to transform these learnings into actionable items to work on](https://docs.google.com/document/d/1lx3YsXntpioEAfC0S2DPcO30iZ-fa01L3x5ge5z3Nmk/edit?usp=sharing)

**Ideas**

- WeChat Payment → get Chinese people to buy BTC on Bisq (will spread like wildfire)
- Venmo support for young generation
- Absolute minimum in order not to scare off first users: 20 offers (10/10), &gt; 5BTC, &lt; 3% Spread
- Offering pro traders free trading fees for the first month (pitch: no cost, decentralized, privacy)

**Outcome**

- We will provide liquidity to the market. Everyone who committed in the call is putting two offers into Bisq (one on each side - buy/sell) - starting Thursday, 7/12/2017. Whenever there is an offer taken we put another one in. We do this for one week and see how it influenced the trading volume.
- Add &quot;research for payment methods&quot; to issues in /growth repository.
- Attract traders from Localbitcoins.com with a comprehensive pitch (approaching localbitcoins.com traders → easy to filter them through research on their website, get contact details and have maybe a short video chat)

The entire log of the growth call:
https://docs.google.com/document/d/19gMJKJa1oJ3UURqOTAOva5EglUr-7AQOluf1IQZ_ZWE/edit?usp=sharing

**Comment by cbeams** [comment]
Thanks everyone who attended, and thanks @csacher for recording and transcribing notes from the call above! Are we ready to close this issue, then? The experiment we're setting out on this week is captured in #12, and I think it would be best to capture any other actions as separate issues at this point. I'll leave this open for a little while in case anyone thinks differently about it.
